### ISSUE TITLE
Do not just dump jars in .local/lib

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/installation#12]
It seems like currently the install script just unpacks the archive in `.local`. Effectively, this dumps all jars in `.local/lib`. I think this is a bad idea for multiple reasons:
- Without any kind of namespacing, there is a risk of overwriting other files in `.local/lib`.
- Other jars in `.local/lib` could end up on our classpath.
- It is difficult to figure out which files are installed by LF, and therefore it is difficult to uninstall.
- We cannot easily remove old contents before installing an updated version. This can create all kind of weird side-effects.

A more robust approach would be to unpack the archive in `.local/share/lf-cli` (or something along those lines) and add symbolic links, e.g., from `./local/bin/lfc` to `./local/share/lf-cli/bin/lfc`. Then we can easily delete the `.local/share/lf-cli` before (re)installing.

**Comment by lhstrh** [comment]
Right, this is exactly what I was thinking. Initially, I thought that a solution would be to change the directory structure in the produced archive (i.e., have `bin` and `lib/lingua-franca/...` instead of just `bin` and `lib`), but looking at the Gradle docs, this doesn't seem straightforward. Installing in a `share` directory and creating symlinks, on the other hands, is easy to do. I'll go ahead and implement this.
